backend/src/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
  path('', views.Index.as_view(), name='index'),
  path('login/', views.LoginPage.as_view(), name='login'),
  path('logout/', views.LogoutPage.as_view(), name='logout'),
  path('profile/show/<int:pk>', views.UserProfilePage.as_view(), name='user_profile'),
  path('profile/update/<int:pk>', views.UpdateUserProfile.as_view(), name='update_profile'),
]

backend/src/stock/urls.py
from django.urls import path
from . import views

app_name = 'stock'

urlpatterns = [
  path('', views.Dashboard.as_view(), name='dashboard'),
  path('investment-history', views.InvestmentHistory.as_view(), name='investment_history'),
  path('ajax/stock', views.StockAjaxResponse.as_view(), name='ajax_stock'),
  # Cash
  path('list/cashes', views.ListCash.as_view(), name='list_cash'),
  path('register/cash', views.RegisterCash.as_view(), name='register_cash'),
  path('update/cash/<int:pk>', views.UpdateCash.as_view(), name='update_cash'),
  path('delete/cash/<int:pk>', views.DeleteCash.as_view(), name='delete_cash'),
  # Purchased stock
  path('list/purchased-stocks', views.ListPurchasedStock.as_view(), name='list_purchased_stock'),
  path('register/purchased-stock', views.RegisterPurchasedStock.as_view(), name='register_purchased_stock'),
  path('update/purchased-stock/<int:pk>', views.UpdatePurchasedStock.as_view(), name='update_purchased_stock'),
  path('delete/purchased-stock/<int:pk>', views.DeletePurchasedStock.as_view(), name='delete_purchased_stock'),
  path('upload/purchased-stock/csv', views.UploadCsvPurchasedStock.as_view(), name='upload_purchased_stock_csv'),
  path('download/purchased-stock/csv', views.DownloadCsvPurchasedStock.as_view(), name='download_purchased_stock_csv'),
  # Snapshot
  path('list/snapshots', views.ListSnapshot.as_view(), name='list_snapshot'),
  path('register/snapshot', views.RegisterSnapshot.as_view(), name='register_snapshot'),
  path('update/snapshot/<int:pk>', views.UpdateSnapshot.as_view(), name='update_snapshot'),
  path('delete/snapshot/<int:pk>', views.DeleteSnapshot.as_view(), name='delete_snapshot'),
  path('update/all-snapshots', views.AjaxUpdateAllSnapshots.as_view(), name='update_all_snapshots'),
  path('detail/snapshot/<int:pk>', views.DetailSnapshot.as_view(), name='detail_snapshot'),
  path('upload/snapshot/json', views.UploadJsonFormatSnapshot.as_view(), name='upload_jsonformat_snapshot'),
  path('download/snapshot/csv/<int:pk>', views.DownloadCsvSnapshot.as_view(), name='download_csv_snapshot'),
  path('download/snapshot/json/<int:pk>', views.DownloadJsonSnapshot.as_view(), name='download_json_snapshot'),
  # Periodic task for snapshot
  path('list/periodic-snapshot-task', views.ListPeriodicTaskForSnapshot.as_view(), name='list_snapshot_task'),
  path('register/periodic-snapshot-task', views.RegisterPeriodicTaskForSnapshot.as_view(), name='register_snapshot_task'),
  path('update/periodic-snapshot-task/<int:pk>', views.UpdatePeriodicTaskForSnapshot.as_view(), name='update_snapshot_task'),
  path('delete/periodic-snapshot-task/<int:pk>', views.DeletePeriodicTaskForSnapshot.as_view(), name='delete_snapshot_task'),
  # Stock
  path('list/stocks', views.ListStock.as_view(), name='list_stock'),
  path('download/stocks', views.DownloadStockPage.as_view(), name='download_stock'),
  # Explanation
  path('explanation', views.ExplanationPage.as_view(), name='explanation'),
]

backend/src/templates/405.html
{% extends 'err_base.html' %}
{% load i18n %}

{% block content %}
{% include 'breadcrumbs.html' with title=_("405 Method Not Allowed") %}
<div class="p-4">
  <div class="d-flex flex-column justify-content-start">
    <div>
      {% trans "Requested HTTP Method is not allowd." %}
    </div>
    {% if exception %}
    <div class="text-danger">
      {{ exception }}
    </div>
    {% endif %}
    <div>
      {{ block.super }}
    </div>
  </div>
</div>
{% endblock %}

backend/src/templates/base.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|stringformat:'s' }}">
  <head>
    {# Required meta tags #}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Asset Management</title>
    {# Font Awesome #}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
    {# Bootstrap 5.3 #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    {# Tempus Dominus #}
    <link href="https://cdn.jsdelivr.net/npm/@eonasdan/tempus-dominus@6.9.4/dist/css/tempus-dominus.min.css" rel="stylesheet" crossorigin="anonymous">
    <style>
      .custom-min-width {
        min-width: 290px;
      }
      .hidden-arrow::after {
        display: none;
      }
      .custom-boxshadow {
        box-shadow: 0 3px 3px rgba(72, 78, 85, 0.6);
        transition: all 0.2s ease-out;
      }
      .custom-boxshadow:hover {
        box-shadow: 0 10px 10px rgba(72, 78, 85, 0.6);
      }
      .date-container-days div.dow {
        color: #333333 !important;
        font-weight: bold;
      }
      .date-container-days div.day.disabled {
        color: #cfd5db !important;
      }
      .date-container-days div.dow:first-child {
        color: #f00 !important;
      }
      .date-container-days div.dow:nth-child(7) {
        color: #00f !important;
      }
      .date-container-days div.day.weekend {
        color: #f00;
      }
      .date-container-days div.day:nth-child(7n) {
        color: #00f;
      }
      .date-container-days div.day.old.weekend,
      .date-container-days div.day.new.weekend {
        color: #00000060;
      }
      .tempus-dominus-widget {
        width: 20rem;
      }
      .tempus-dominus-widget .date-container-days {
        grid-auto-rows: 2.5rem !important;
      }
    </style>
    {% block header %}
    {% endblock %}
  </head>
  <body class="d-flex flex-column vh-100 custom-min-width bg-body-tertiary">
    <header class="mb-2">
      {% include "header.html" %}
    </header>
    <main class="w-100 mx-auto mb-auto">
      <div class="container">
      {# contents #}
      {% block content %}
      {% endblock %}
      </div>
    </main>
    <footer>
      {% include "footer.html" %}
    </footer>
    {# Popperjs and Bootstrap 5.3 javascript #}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"  crossorigin="anonymous"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" crossorigin="anonymous"
            integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS"></script>
    {# Tempus Dominus #}
    <script src="https://cdn.jsdelivr.net/npm/@eonasdan/tempus-dominus@6.9.4/dist/js/tempus-dominus.min.js" crossorigin="anonymous"></script>
    {% block bodyjs %}
    <script>
      class HelperMethods {
        constructor() {
          this.getCookie = this.getCookie.bind(this);
          this.registerDeleteModalEvent = this.registerDeleteModalEvent.bind(this);
          this.setupPicker = this.setupPicker.bind(this);
          this.setupDownloadStatus = this.setupDownloadStatus.bind(this);
        }
        getCookie(name) {
          let cookieValue = null;

          if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');

            for (const cookie of cookies) {
              if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
              }
            }
          }

          return cookieValue;
        }
        registerDeleteModalEvent(args) {
          const {targetCSS, formID, modalID} = args;
          const deleteBtns = document.querySelectorAll(`.${targetCSS}`);
          const deleteForm = document.getElementById(formID);
          const targetField = document.getElementById('target-name');

          for (const btn of deleteBtns) {
            btn.addEventListener('click', (event) => {
              deleteForm.action = btn.dataset.url;
              targetField.textContent = btn.dataset.name;
              const modal = new bootstrap.Modal(`#${modalID}`);
              modal.show();
            });
          }
        }
        setupPicker(element) {
          // Process of purchase data field
          const pickerCallback = (event, target) => {
            if (!event.isClear && event.isValid && event.date) {
              target.viewDate = event.date;
            }
          };
          const picker = new tempusDominus.TempusDominus(element, {
            localization: {
              format: 'yyyy/MM/dd',
              dayViewHeaderFormat: { year: 'numeric', month: 'long' },
            },
            display: {
              components: {
                clock: false,
              },
              buttons: {
                close: true,
              },
              icons: {
                type:     'icons',
                date:     'fas fa-calendar-week',
                up:       'fas fa-arrow-up',
                down:     'fas fa-arrow-down',
                previous: 'fas fa-chevron-left',
                next:     'fas fa-chevron-right',
                clear:    'fas fa-trash',
                close:    'fas fa-x',
              },
              viewMode: 'calendar',
            },
          });
          picker.subscribe('change.td', function (event) {pickerCallback(event, this);});
          // Register focus event and click event
          let isFocused = false;
          element.addEventListener('focusin', function (event) {
            isFocused = true;

            window.setTimeout(() => {
              if (isFocused) {
                this.click();
              }
              isFocused = false;
            }, 200);
          });
          element.addEventListener('click', (envet) => {
            isFocused = false;
          });
          document.addEventListener('keyup', (event) => {
            if (event.key === 'Escape') {
              picker.hide();
            }
          });

          return picker;
        }
        setupDownloadStatus(key, option, callback) {
          // Setup timer
          const timerId = window.setInterval(() => {
            // Check whether targetCookieValue exists or not
            const target = `${key}=completed`;

            if (document.cookie.includes(target)) {
              window.clearInterval(timerId);
              callback();
              // Execute post-process
              document.cookie = `${key}=; max-age=0; path=/; ${option}`;
            }
          }, 1000);
        }
      }
    </script>
    {% endblock %}
  </body>
</html>

backend/src/templates/breadcrumbs.html
<div class="row">
  <div class="col">
    <h2>{{ title }}</h2>
  </div>
</div>
<div class="row">
  <div class="col">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
      {% for item in view.resolve_crumbles %}
        {% if forloop.last %}
        <li class="breadcrumb-item active" aria-current="page">{{ item.title }}</li>
        {% else %}
        <li class="breadcrumb-item">
          {% if item.url %}
            <a href="{{ item.url }}">{{ item.title }}</a>
          {% else %}
            {{ item.title }}
          {% endif %}
        </li>
        {% endif %}
      {% endfor %}
      </ol>
    </nav>
  </div>
</div>

backend/src/templates/delete_modal_form.html
{% load i18n %}

<div class="modal" id="{{ modal_id }}" tabindex="-1" aria-labelledby="deletion-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <p class="modal-title fs-5" id="deletion-label">{% trans "Confirmation of deletion" %}</p>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p class="text-danger"><strong>{% trans "May I really delete this record?" %}</strong></p>
        <p>{% trans "target" %}: <span id="target-name" class="text-break"></span></p>
      </div>
      <div class="modal-footer">
        <form method="POST" action="" id="{{ form_id }}" class="w-100">
          {% csrf_token %}
          <div class="row g-2">
            <div class="col-12 col-md-6">
              <button type="submit" class="btn btn-danger w-100 custom-boxshadow">
                {% trans "Accept" %}
              </button>
            </div>
            <div class="col-12 col-md-6">
              <button type="button" class="btn btn-secondary w-100 custom-boxshadow" data-bs-dismiss="modal">
                {% trans "Close" %}
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

backend/src/templates/err_base.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|stringformat:'s' }}">
  <head>
    {# Required meta tags #}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>Asset Management</title>
    {# Font Awesome #}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
    {# Bootstrap 5.3 #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <style>
      .custom-min-width {
        min-width: 290px;
      }
      .custom-boxshadow {
        box-shadow: 0 3px 3px rgba(72, 78, 85, 0.6);
        transition: all 0.2s ease-out;
      }
      .custom-boxshadow:hover {
        box-shadow: 0 10px 10px rgba(72, 78, 85, 0.6);
      }
    </style>
    {% block header %}
    {% endblock %}
  </head>
  <body class="d-flex flex-column vh-100 custom-min-width bg-body-tertiary">
    <header class="mb-2">
      {% include "header.html" %}
    </header>
    <main class="w-100 mx-auto mb-auto">
      <div class="container">
        {% block content %}
        <p>
          {% blocktrans %}Redirect to the top page after <span id="rest-count">30</span> seconds.{% endblocktrans  %}
        </p>
        <p>
          <a href="{% url 'account:index' %}" class="btn btn-secondary custom-boxshadow">
            {% trans "Back to top page" %}
          </a>
        </p>
        {% endblock %}
      </div>
    </main>
    <footer>
      {% include "footer.html" %}
    </footer>
    {# Popperjs and Bootstrap 5.3 javascript #}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"  crossorigin="anonymous"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" crossorigin="anonymous"
            integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS"></script>
    <script>
      // redirect process
      (function(){
        const init = () => {
          const element = document.getElementById('rest-count');
          const timerId = setInterval(() => {
            const count = Number(element.textContent);
            element.textContent = count - 1;
            // Check counter
            if (count <= 1) {
              window.location.href = "{% url 'account:index' %}";
              clearInterval(timerId);
            }
          }, 1000);
        };
        // Add DOM event
        document.addEventListener('DOMContentLoaded', init);
      }());
    </script>
    {% block bodyjs %}
    {% endblock %}
  </body>
</html>

backend/src/templates/footer.html
<div class="text-center text-md-start text-muted">
  {# Copyright #}
  <div class="text-center p-3 bg-body-secondary">
    <span>&copy; 2025 Copyright:</span>
    <a class="text-reset fw-bold" href="{% url 'account:index' %}">Asset Management</a>
  </div>
</div>

backend/src/templates/header.html
{% load i18n %}
{% load custom_tags %}

<nav id="main-navbar" class="navbar navbar-expand-md navbar-light bg-white">
  <div class="container-fluid align-items-center">
    {# Navbar brand #}
    <a class="navbar-brand" href="{% url 'account:index' %}">
      <i class="fa-solid fa-earth-asia"></i><span class="px-2">{% trans "Asset Management" %}</span>
    </a>

    {# Left links #}
    <ul class="navbar-nav me-auto">
      {% if not user.is_authenticated %}
      <li class="nav-item dropdown">
        <a
          href="#"
          class="nav-link dropdown-toggle d-flex align-items-center"
          role="button"
          aria-expanded="false"
          data-bs-toggle="dropdown"
        >
          <span>Language</span>
        </a>
        <ul class="dropdown-menu">
          {% get_available_languages as LANGUAGES %}
          {% get_language_info_list for LANGUAGES as languages %}
          {% for language in languages %}
          <li>
            <a class="dropdown-item" href="/{{ language.code }}">
              {{ language.name_local }} ({{ language.code }})
            </a>
          </li>
          {% endfor %}
        </ul>
      </li>
      {% endif %}
    </ul>

    {# Right elements #}
    <div class="d-flex align-items-center">
      {% if user.is_authenticated %}
      {# Avatar #}
      <div class="dropdown">
        <a
          href="#"
          class="dropdown-toggle d-flex align-items-center hidden-arrow "
          role="button"
          aria-expanded="false"
          data-bs-toggle="dropdown"
        >
          <span class="text-primary opacity-75">
            <i class="far fa-circle-user fa-2x"></i>
          </span>
        </a>
        <ul class="dropdown-menu dropdown-menu-end">
          {# User profile #}
          <li>
            <a class="dropdown-item" href="{% url 'account:user_profile' pk=user.pk %}">
              {% trans "User Profile" %}
            </a>
          </li>
          {# Logout button #}
          <li><hr class="dropdown-divider" /></li>
          <li>
            <form action="{% url 'account:logout' %}" method="POST" id="logout-form">
              {% csrf_token %}
              <button type="submit" class="dropdown-item">{% trans "Logout" %}</button>
            </form>
          </li>
        </ul>
      </div>
      {% else %}
      <a class="" href="{% url 'account:login' %}">{% trans "Login" %}</a>
      {% endif %}
    </div>
  </div>
</nav>