backend/src/stock/urls.py
from django.urls import path
from . import views

app_name = 'stock'

urlpatterns = [
  path('', views.Dashboard.as_view(), name='dashboard'),
  path('investment-history', views.InvestmentHistory.as_view(), name='investment_history'),
  path('ajax/stock', views.StockAjaxResponse.as_view(), name='ajax_stock'),
  # Cash
  path('list/cashes', views.ListCash.as_view(), name='list_cash'),
  path('register/cash', views.RegisterCash.as_view(), name='register_cash'),
  path('update/cash/<int:pk>', views.UpdateCash.as_view(), name='update_cash'),
  path('delete/cash/<int:pk>', views.DeleteCash.as_view(), name='delete_cash'),
  # Purchased stock
  path('list/purchased-stocks', views.ListPurchasedStock.as_view(), name='list_purchased_stock'),
  path('register/purchased-stock', views.RegisterPurchasedStock.as_view(), name='register_purchased_stock'),
  path('update/purchased-stock/<int:pk>', views.UpdatePurchasedStock.as_view(), name='update_purchased_stock'),
  path('delete/purchased-stock/<int:pk>', views.DeletePurchasedStock.as_view(), name='delete_purchased_stock'),
  path('upload/purchased-stock/csv', views.UploadCsvPurchasedStock.as_view(), name='upload_purchased_stock_csv'),
  path('download/purchased-stock/csv', views.DownloadCsvPurchasedStock.as_view(), name='download_purchased_stock_csv'),
  # Snapshot
  path('list/snapshots', views.ListSnapshot.as_view(), name='list_snapshot'),
  path('register/snapshot', views.RegisterSnapshot.as_view(), name='register_snapshot'),
  path('update/snapshot/<int:pk>', views.UpdateSnapshot.as_view(), name='update_snapshot'),
  path('delete/snapshot/<int:pk>', views.DeleteSnapshot.as_view(), name='delete_snapshot'),
  path('update/all-snapshots', views.AjaxUpdateAllSnapshots.as_view(), name='update_all_snapshots'),
  path('detail/snapshot/<int:pk>', views.DetailSnapshot.as_view(), name='detail_snapshot'),
  path('upload/snapshot/json', views.UploadJsonFormatSnapshot.as_view(), name='upload_jsonformat_snapshot'),
  path('download/snapshot/csv/<int:pk>', views.DownloadCsvSnapshot.as_view(), name='download_csv_snapshot'),
  path('download/snapshot/json/<int:pk>', views.DownloadJsonSnapshot.as_view(), name='download_json_snapshot'),
  # Periodic task for snapshot
  path('list/periodic-snapshot-task', views.ListPeriodicTaskForSnapshot.as_view(), name='list_snapshot_task'),
  path('register/periodic-snapshot-task', views.RegisterPeriodicTaskForSnapshot.as_view(), name='register_snapshot_task'),
  path('update/periodic-snapshot-task/<int:pk>', views.UpdatePeriodicTaskForSnapshot.as_view(), name='update_snapshot_task'),
  path('delete/periodic-snapshot-task/<int:pk>', views.DeletePeriodicTaskForSnapshot.as_view(), name='delete_snapshot_task'),
  # Stock
  path('list/stocks', views.ListStock.as_view(), name='list_stock'),
  path('download/stocks', views.DownloadStockPage.as_view(), name='download_stock'),
  # Explanation
  path('explanation', views.ExplanationPage.as_view(), name='explanation'),
]

backend/src/stock/views.py
from django.views.generic import (
  TemplateView,
  ListView,
  UpdateView,
  DeleteView,
  DetailView,
  View,
  FormView,
)
from django.conf import settings
from django.core.exceptions import NON_FIELD_ERRORS
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.utils.translation import gettext_lazy
from django.http import JsonResponse, StreamingHttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django_celery_beat.models import PeriodicTask
from utils.views import (
  BaseCreateUpdateView,
  CreateViewBasedOnUser,
  UpdateViewBasedOnUser,
  CustomDeleteView,
  DjangoBreadcrumbsMixin,
)
from account.views import Index
from . import models, forms
from utils.models import streaming_csv_file

class Dashboard(LoginRequiredMixin, ListView, DjangoBreadcrumbsMixin):
  model = models.Snapshot
  template_name = 'stock/dashboard.html'
  context_object_name = 'snapshots'
  crumbles = DjangoBreadcrumbsMixin.get_target_crumbles(
    url_name='stock:dashboard',
    title=gettext_lazy('Dashboard'),
    parent_view_class=Index,
  )

  def get_queryset(self):
    user = self.request.user
    queryset = user.snapshots.all()

    return queryset

class InvestmentHistory(Dashboard):
  template_name = 'stock/investment_history.html'
  crumbles = DjangoBreadcrumbsMixin.get_target_crumbles(
    url_name='stock:investment_history',
    title=gettext_lazy('Investment history'),
    parent_view_class=Index,
  )

class StockAjaxResponse(View):
  raise_exception = True
  http_method_names = ['get']

  def get(self, request, *args, **kwargs):
    data = models.Stock.get_choices_as_list()
    response = JsonResponse({'qs': data})

    return response

class ListCash(LoginRequiredMixin, ListView, DjangoBreadcrumbsMixin):
  model = models.Cash
  template_name = 'stock/cashes.html'
  paginate_by = 24
  context_object_name = 'cashes'
  crumbles = DjangoBreadcrumbsMixin.get_target_crumbles(
    url_name='stock:list_cash',
    title=gettext_lazy('Cash list'),
    parent_view_class=Index,
  )

  def get_queryset(self):
    user = self.request.user
    queryset = user.cashes.all()

    return queryset

class RegisterCash(CreateViewBasedOnUser, DjangoBreadcrumbsMixin):
  model = models.Cash
  form_class = forms.CashForm
  template_name = 'stock/cash_form.html'
  success_url = reverse_lazy('stock:list_cash')
  crumbles = DjangoBreadcrumbsMixin.get_target_crumbles(
    url_name='stock:register_cash',
    title=gettext_lazy('Register cash'),
    parent_view_class=ListCash,
  )

class UpdateCash(UpdateViewBasedOnUser, DjangoBreadcrumbsMixin):
  model = models.Cash
  form_class = forms.CashForm
  template_name = 'stock/cash_form.html'
  success_url = reverse_lazy('stock:list_cash')
  crumbles = DjangoBreadcrumbsMixin.get_target_crumbles(
    url_name='stock:update_cash',
    title=gettext_lazy('Update cash'),
    parent_view_class=ListCash,
    url_keys=['pk'],
  )

class DeleteCash(CustomDeleteView, DjangoBreadcrumbsMixin):
  model = models.Cash
  success_url = reverse_lazy('stock:list_cash')

class ListPurchasedStock(LoginRequiredMixin, ListView, DjangoBreadcrumbsMixin):
  model = models.PurchasedStock
  template_name = 'stock/purchased_stocks.html'
  form_class = forms.PurchasedStockFilteringForm
  paginate_by = 20
  context_object_name = 'pstocks'
  crumbles = DjangoBreadcrumbsMixin.get_target_crumbles(
    url_name='stock:list_purchased_stock',
    title=gettext_lazy('purchased stock list'),
    parent_view_class=Index,
  )

  def get_queryset(self):
    user = self.request.user
    params = self.request.GET.copy() or {}
    self.form = self.form_class(data=params)
    queryset = self.form.get_queryset_with_condition(user)

    return queryset

  def get_context_data(self, **kwargs):
    is_secure = getattr(settings, 'IS_SECURE_COOKIE', True)
    context = super().get_context_data(**kwargs)
    context['form'] = self.form
    context['download_form'] = forms.DownloadCsvPurchasedStockForm()
    context['is_secure'] = 'Secure' if is_secure else ''

    return context

class RegisterPurchasedStock(CreateViewBasedOnUser, DjangoBreadcrumbsMixin):
  model = models.PurchasedStock
  form_class = forms.PurchasedStockForm
  template_name = 'stock/purchased_stock_form.html'
  success_url = reverse_lazy('stock:list_purchased_stock')
  crumbles = DjangoBreadcrumbsMixin.get_target_crumbles(
    url_name='stock:register_purchased_stock',
    title=gettext_lazy('Register purchased stock'),
    parent_view_class=ListPurchasedStock,
  )

class UpdatePurchasedStock(UpdateViewBasedOnUser, DjangoBreadcrumbsMixin):
  model = models.PurchasedStock
  form_class = forms.PurchasedStockForm
  template_name = 'stock/purchased_stock_form.html'
  success_url = reverse_lazy('stock:list_purchased_stock')
  crumbles = DjangoBreadcrumbsMixin.get_target_crumbles(
    url_name='stock:update_purchased_stock',
    title=gettext_lazy('Update purchased stock'),
    parent_view_class=ListPurchasedStock,
    url_keys=['pk'],
  )

  def get_form(self):
    form = super().get_form()
    form.update_queryset(self.kwargs['pk'])

    return form

class DeletePurchasedStock(CustomDeleteView, DjangoBreadcrumbsMixin):
  model = models.PurchasedStock
  success_url = reverse_lazy('stock:list_purchased_stock')

class UploadCsvPurchasedStock(LoginRequiredMixin, FormView, DjangoBreadcrumbsMixin):
  form_class = forms.UploadCsvPurchasedStockForm
  template_name = 'stock/upload_purchased_stock_with_csvformat.html'
  success_url = reverse_lazy('stock:list_purchased_stock')
  crumbles = DjangoBreadcrumbsMixin.get_target_crumbles(
    url_name='stock:upload_purchased_stock_csv',
    title=gettext_lazy('Upload purchased stock (CSV format)'),
    parent_view_class=ListPurchasedStock,
  )

  def form_valid(self, form):
    form.register(self.request.user)
    # Check errors
    if not form.has_error(NON_FIELD_ERRORS):
      response = super().form_valid(form)
    else:
      response = super().form_invalid(form)

    return response

class DownloadCsvPurchasedStock(LoginRequiredMixin, FormView):
  raise_exception = True
  http_method_names = ['post']
  form_class = forms.DownloadCsvPurchasedStockForm

  def form_valid(self, form):
    user = self.request.user
    kwargs = form.create_response_kwargs(user)
    # Create response
    max_age = getattr(settings, 'CSV_DOWNLOAD_MAX_AGE', 5 * 60)
    is_secure = getattr(settings, 'IS_SECURE_COOKIE', True)
    filename = kwargs['filename']
    response = StreamingHttpResponse(
      streaming_csv_file(kwargs['rows'], header=kwargs['header']),
      content_type='text/csv;charset=UTF-8',
      headers={'Content-Disposition': f'attachment; filename="{filename}"'},
    )
    response.set_cookie(
      'purchased_stock_download_status',
      value='completed',
      max_age=max_age,
      secure=is_secure,
    )

    return response

class ListSnapshot(LoginRequiredMixin, ListView, DjangoBreadcrumbsMixin):
  model = models.Snapshot
  template_name = 'stock/snapshots.html'
  paginate_by = 36
  context_object_name = 'snapshots'
  crumbles = DjangoBreadcrumbsMixin.get_target_crumbles(
    url_name='stock:list_snapshot',
    title=gettext_lazy('Snapshot list'),
    parent_view_class=Index,
  )

  def get_queryset(self):
    user = self.request.user
    queryset = user.snapshots.all()

    return queryset

class RegisterSnapshot(CreateViewBasedOnUser, DjangoBreadcrumbsMixin):
  model = models.Snapshot
  form_class = forms.SnapshotForm
  template_name = 'stock/snapshot_form.html'
  success_url = reverse_lazy('stock:list_snapshot')
  crumbles = DjangoBreadcrumbsMixin.get_target_crumbles(
    url_name='stock:register_snapshot',
    title=gettext_lazy('Register snapshot'),
    parent_view_class=ListSnapshot,
  )

class UpdateSnapshot(UpdateViewBasedOnUser, DjangoBreadcrumbsMixin):
  model = models.Snapshot
  form_class = forms.SnapshotForm
  template_name = 'stock/snapshot_form.html'
  success_url = reverse_lazy('stock:list_snapshot')
  crumbles = DjangoBreadcrumbsMixin.get_target_crumbles(
    url_name='stock:update_snapshot',
    title=gettext_lazy('Update snapshot'),
    parent_view_class=ListSnapshot,
    url_keys=['pk'],
  )

class DeleteSnapshot(CustomDeleteView):
  model = models.Snapshot
  success_url = reverse_lazy('stock:list_snapshot')

class AjaxUpdateAllSnapshots(View):
  raise_exception = True
  http_method_names = ['post']

  def post(self, request, *args, **kwargs):
    try:
      models.Snapshot.save_all(request.user)
      data = {'status': True}
    except:
      data = {'status': False}
    response = JsonResponse(data)

    return response

class IsSnapshotOwner(UserPassesTestMixin):
  def test_func(self):
    pk = self.kwargs['pk']
    user = self.request.user
    queryset = user.snapshots.all().filter(pk=pk)
    is_valid = queryset.exists()

    return is_valid

class DetailSnapshot(LoginRequiredMixin, IsSnapshotOwner, DetailView, DjangoBreadcrumbsMixin):
  raise_exception = True
  model = models.Snapshot
  context_object_name = 'snapshot'
  template_name = 'stock/specific_snapshot.html'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    instance = context[self.context_object_name]
    # Set breadcrumbs
    self.crumbles = DjangoBreadcrumbsMixin.get_target_crumbles(
      url_name='stock:detail_snapshot',
      title=instance.title,
      parent_view_class=ListSnapshot,
      url_keys=['pk'],
    )

    return context

class UploadJsonFormatSnapshot(LoginRequiredMixin, FormView, DjangoBreadcrumbsMixin):
  form_class = forms.UploadJsonFormatSnapshotForm
  template_name = 'stock/upload_jsonformat_snapshot.html'
  success_url = reverse_lazy('stock:list_snapshot')
  crumbles = DjangoBreadcrumbsMixin.get_target_crumbles(
    url_name='stock:upload_jsonformat_snapshot',
    title=gettext_lazy('Upload snapshot (JSON format)'),
    parent_view_class=ListSnapshot,
  )

  def get_form_kwargs(self, *args, **kwargs):

backend/src/templates/stock/cashes.html
{% extends 'base.html' %}
{% load i18n %}
{% load humanize %}

{% block content %}
{% include 'breadcrumbs.html' with title=_("Cashes") %}
<div class="row justify-content-center">
  <div class="col">
    <div class="row row-cols-1 g-2">
      <div class="col">
        <a
          href="{% url 'stock:register_cash' %}"
          class="btn btn-primary w-100 custom-boxshadow"
        >
          {% trans "Register cash" %}
        </a>
      </div>
      <div class="col">
        {% if cashes %}
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">{% trans "No." %}</th>
                <th scope="col">{% trans "Balance" %}</th>
                <th scope="col">{% trans "Registered date" %}</th>
                <th colspan="2" class="text-center">{% trans "Operate" %}</th>
              </tr>
            </thead>
            <tbody class="table-group-divider">
              {% for instance in cashes %}
              <tr>
                <td scope="row">{{ page_obj.start_index|add:forloop.counter0 }}</td>
                <td data-type="balance">{{ instance.balance|intcomma }}</td>
                <td data-type="registeredDate">{{ instance.registered_date|date:"Y-m-d" }}</td>
                <td data-operate="edit" class="text-center">
                  <a
                    href="{% url 'stock:update_cash' pk=instance.pk %}"
                    class="btn btn-link px-1 py-0 text-success link-underline link-underline-opacity-0"
                  >
                    <i class="fas fa-edit fa-lg"></i>
                  </a>
                </td>
                <td data-operate="delete" class="text-center">
                  <button
                    class="btn btn-link px-1 py-0 text-danger delete-target-record"
                    data-name="[{{ instance.registered_date|date:'Y-m-d' }}] {{ instance.balance|intcomma }}"
                    data-url="{% url 'stock:delete_cash' pk=instance.pk %}"
                  >
                    <i class="fas fa-trash fa-lg"></i>
                  </button>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        {% else %}
        <span>{% trans "There is no cashes. Please add the items from the above button." %}</span>
        {% endif %}
      </div>
      <div class="col">
      {% include "renderer/custom_pagenate.html" with page_obj=page_obj %}
      </div>
    </div>
  </div>
</div>

{% include "delete_modal_form.html" with modal_id="delete-modal" form_id="delete-form" %}
{% endblock %}

{% block bodyjs %}
{{ block.super }}
<script>
(function () {
  // Define initialization function
  const init = () => {
    const helper = new HelperMethods();
    helper.registerDeleteModalEvent({
      targetCSS: 'delete-target-record',
      formID: 'delete-form',
      modalID: 'delete-modal',
    });
  };
  //
  // Add DOM event
  //
  document.addEventListener('DOMContentLoaded', init);
})();
</script>
{% endblock %}

backend/src/templates/stock/periodic_tasks_for_snapshot.html
{% extends 'base.html' %}
{% load i18n %}
{% load humanize %}

{% block content %}
{% include 'breadcrumbs.html' with title=_("Periodic tasks for snapshot") %}
<div class="row justify-content-center">
  <div class="col">
    <div class="row row-cols-1 g-2">
    {% with snapshot=user.snapshots.all.exists %}
      {% if snapshot %}
      <div class="col">
        <a
          href="{% url 'stock:register_snapshot_task' %}"
          class="btn btn-primary w-100 custom-boxshadow"
        >
          {% trans "Register periodic task for snapshot" %}
        </a>
      </div>
      {% else %}
      <div class="col">
        <a
          href="{% url 'stock:register_snapshot' %}"
          class="btn btn-primary w-100 custom-boxshadow"
        >
          {% trans "Register snapshot" %}
        </a>
      </div>
      {% endif %}
      <div class="col">
        {% if tasks %}
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">{% trans "No." %}</th>
                <th scope="col" class="text-nowrap">{% trans "Task name" %}</th>
                <th scope="col" class="text-nowrap">{% trans "Snapshot name" %}</th>
                <th scope="col" class="text-nowrap">{% trans "Schedule" %}</th>
                <th scope="col" class="text-nowrap">{% trans "Total run count" %}</th>
                <th scope="col" class="text-nowrap">{% trans "Enabled/Disabled" %}</th>
                <th colspan="2" class="text-center">{% trans "Operate" %}</th>
              </tr>
            </thead>
            <tbody class="table-group-divider">
              {% for instance in tasks %}
              <tr>
                {% with table_css=instance.enabled|yesno:',table-secondary' %}
                <td scope="row" class="{{ table_css }}">{{ page_obj.start_index|add:forloop.counter0 }}</td>
                <td data-type="taskName" class="{{ table_css }}">{{ instance.name }}</td>
                <td data-type="snapshotName" class="{{ table_css }}">{{ instance.description }}</td>
                <td data-type="schedule" class="{{ table_css }}">{{ instance.scheduler }}</td>
                <td data-type="totalRunCount" class="{{ table_css }}">{{ instance.total_run_count|intcomma }}</td>
                <td data-type="isEnabled" class="{{ table_css }}">{% if instance.enabled %}{% trans "Enabled" %}{% else %}{% trans "Disabled" %}{% endif %}</td>
                {% endwith %}
                <td data-operate="edit" class="text-center">
                  <a
                    href="{% url 'stock:update_snapshot_task' pk=instance.pk %}"
                    class="btn btn-link px-1 py-0 text-success link-underline link-underline-opacity-0"
                  >
                    <i class="fas fa-edit fa-lg"></i>
                  </a>
                </td>
                <td data-operate="delete" class="text-center">
                  <button
                    class="btn btn-link px-1 py-0 text-danger delete-target-record"
                    data-name="{{ instance.name }} ({% if instance.enabled %}{% trans 'Enabled' %}{% else %}{% trans 'Disabled' %}{% endif %})"
                    data-url="{% url 'stock:delete_snapshot_task' pk=instance.pk %}"
                  >
                    <i class="fas fa-trash fa-lg"></i>
                  </button>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        {% elif snapshot %}
        <span>{% trans "There is no periodic tasks for snapshot. Please add the tasks from the above button." %}</span>
        {% else %}
        <span>{% trans "There is no snapshots. Please add the snapshots from the above button." %}</span>
        {% endif %}
      </div>
      <div class="col">
      {% include "renderer/custom_pagenate.html" with page_obj=page_obj %}
      </div>
    {% endwith %}
    </div>
  </div>
</div>

{# Delete-modal #}
{% include "delete_modal_form.html" with modal_id="delete-modal" form_id="delete-form" %}
{% endblock %}

{% block bodyjs %}
{{ block.super }}
<script>
(function () {
  // Define initialization function
  const init = () => {
    const helper = new HelperMethods();
    helper.registerDeleteModalEvent({
      targetCSS: 'delete-target-record',
      formID: 'delete-form',
      modalID: 'delete-modal',
    });
  };
  //
  // Add DOM event
  //
  document.addEventListener('DOMContentLoaded', init);
})();
</script>
{% endblock %}

backend/src/templates/stock/snapshots.html
{% extends 'base.html' %}
{% load i18n %}
{% load humanize %}

{% block content %}
{% include 'breadcrumbs.html' with title=_("Snapshots") %}
<div class="row justify-content-center">
  <div class="col">
    <div class="row row-cols-1 g-2">
      <div class="col">
        <a
          href="{% url 'stock:register_snapshot' %}"
          class="btn btn-primary w-100 custom-boxshadow"
        >
          {% trans "Register snapshot" %}
        </a>
      </div>
      <div class="col">
        <a
          href="{% url 'stock:upload_jsonformat_snapshot' %}"
          class="btn btn-success w-100 custom-boxshadow"
        >
          {% trans "Upload snapshot (JSON format)" %}
        </a>
      </div>
      {% comment %}
      <div class="col">
        <button
          type="button"
          id="update-all-snapshots"
          class="btn btn-success w-100 custom-boxshadow"
        >
          {% trans "Update all snapshots" %}
        </button>
      </div>
      {% endcomment %}
      <div class="col">
        {% if snapshots %}
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">{% trans "No." %}</th>
                <th scope="col" class="text-nowrap">{% trans "Title" %}</th>
                <th scope="col" class="text-nowrap">{% trans "Start date" %}</th>
                <th scope="col" class="text-nowrap">{% trans "End date" %}</th>
                <th colspan="4" class="text-center">{% trans "Operate" %}</th>
              </tr>
            </thead>
            <tbody class="table-group-divider">
              {% for instance in snapshots %}
              <tr>
                <td scope="row">{{ page_obj.start_index|add:forloop.counter0 }}</td>
                <td data-type="title">
                  <a
                    href="{% url 'stock:detail_snapshot' pk=instance.pk %}"
                    class="text-primary link-underline link-underline-opacity-0"
                  >
                    {{ instance.title }}
                  </a>
                </td>
                <td data-type="startDate">{{ instance.start_date|date:"Y-m-d" }}</td>
                <td data-type="endDate">{{ instance.end_date|date:"Y-m-d" }}</td>
                <td data-operate="download" class="text-center">
                  <a
                    href="{% url 'stock:download_csv_snapshot' pk=instance.pk %}"
                    class="btn btn-link px-1 py-0 text-primary link-underline link-underline-opacity-0"
                    data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="{% trans 'Download as CSV' %}"
                  >
                    <i class="fas fa-file-csv fa-lg"></i>
                  </a>
                </td>
                <td data-operate="download" class="text-center">
                  <a
                    href="{% url 'stock:download_json_snapshot' pk=instance.pk %}"
                    class="btn btn-link px-1 py-0 text-warning link-underline link-underline-opacity-0"
                    data-bs-toggle="tooltip" data-bs-placement="top" data-bs-title="{% trans 'Download as JSON' %}"
                  >
                    <i class="fas fa-file-code fa-lg"></i>
                  </a>
                </td>
                <td data-operate="edit" class="text-center">
                  <a
                    href="{% url 'stock:update_snapshot' pk=instance.pk %}"
                    class="btn btn-link px-1 py-0 text-success link-underline link-underline-opacity-0"
                  >
                    <i class="fas fa-edit fa-lg"></i>
                  </a>
                </td>
                <td data-operate="delete" class="text-center">
                  <button
                    class="btn btn-link px-1 py-0 text-danger delete-target-record"
                    data-name="{{ instance.title }}"
                    data-url="{% url 'stock:delete_snapshot' pk=instance.pk %}"
                  >
                    <i class="fas fa-trash fa-lg"></i>
                  </button>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        {% else %}
        <span>{% trans "There is no snapshots. Please add the items from the above button." %}</span>
        {% endif %}
      </div>
      <div class="col">
      {% include "renderer/custom_pagenate.html" with page_obj=page_obj %}
      </div>
    </div>
  </div>
</div>

{% comment %}
{# Output modal #}
<div class="modal" id="output-modal" tabindex="-1" aria-labelledby="message-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <p class="modal-title fs-5" id="message-label">{% trans "Result of updating all snapshots" %}</p>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p class="text-danger"><strong>{% trans "Failed to update some snapshots." %}</strong></p>
      </div>
      <div class="modal-footer">
        <div class="row">
          <div class="col-12">
            <button type="button" class="btn btn-secondary w-100 custom-boxshadow" data-bs-dismiss="modal">
              {% trans "Close" %}
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endcomment %}

{# Delete-modal #}
{% include "delete_modal_form.html" with modal_id="delete-modal" form_id="delete-form" %}
{% endblock %}

{% block bodyjs %}
{{ block.super }}
<script>
(function () {
  // Define initialization function
  const init = () => {
    const helper = new HelperMethods();
    // Register delete modal event
    helper.registerDeleteModalEvent({
      targetCSS: 'delete-target-record',
      formID: 'delete-form',
      modalID: 'delete-modal',
    });
    // Define popper event
    const tooltipElements = document.querySelectorAll('[data-bs-toggle="tooltip"]');
    [...tooltipElements].map((elem) => new bootstrap.Tooltip(elem));
    {% comment %}
    // Add update-snapshot event
    const updateSnapshots = document.getElementById('update-all-snapshots');
    updateSnapshots.addEventListener('click', async (event) => {
      event.target.disabled = true;
      const url = '{% url "stock:update_all_snapshots" %}';
      const csrfToken = helper.getCookie('csrftoken');
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json; charset=utf-8',
          'X-CSRFToken': csrfToken,
        },
      });
      const data = await response.json();

      if (!data.status) {
        const modal = new bootstrap.Modal('#output-modal');
        modal.show();
      }
      event.target.disabled = false;
    });
    {% endcomment %}
  };
  //
  // Add DOM event
  //
  document.addEventListener('DOMContentLoaded', init);
})();
</script>
{% endblock %}